### ISSUE TITLE
execute doesn't work with graphql-tools

### ISSUE THREAD

**Issue by yaacovCR** [yaacovCR/apollo-stitcher#2]
graphql-tools-fork has been merged into upstream graphql-tools
Latest changes in both complicate direct execution, as argument defaults are now copied perfectly from existing info object, but cannot be faked very well without a source schema/info object.

**Comment by saerdnaer** [comment]
Does this affect https://github.com/yaacovCR/apollo-stitcher/blob/8d4fd0c4fc69a9af5031675f4ec3c5b6ad30ed5d/tutorials/Request%20Specific%20Caching.md ?

**Comment by yaacovCR** [comment]
I don't believe so. This should also be fixed eventually by https://github.com/ardatan/graphql-tools/commit/445cef15511f1373eee73cf7edcfb81259615779

**Comment by yaacovCR** [comment]
@saerdnaer see updated docs for per request caching with GraphQL tools v6

**Comment by yaacovCR** [comment]
Closed by apollo-stitcher v0.4 with graphql-tools v6
